# dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'alpaca-tc/alpaca_powertabline'

[[plugins]]
repo = 'Lokaltog/powerline'

[[plugins]]
repo = "godlygeek/tabular"

[[plugins]]
repo = "Shougo/vimfiler"


[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "Shougo/vimproc"
build = 'make'

[[plugins]]
repo = 'Yggdroot/indentLine'


[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'


[[plugins]]
repo = 'upamune/esa.vim'


