
[[plugins]]
repo = "joker1007/vim-markdown-quote-syntax"
on_ft = ['markdown']

[[plugins]]
repo = "rcmdnk/vim-markdown"
on_ft = ['markdown']

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']
